<?php include '[includes_dir_prefix]includes/setup.php' ?><!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<? include nomad::includesDir()."/head.php" ?>
<!--HEAD-START-->
<!--HEAD-PLACEHOLDER-->
<!--HEAD-END-->
</head>
<body>
<?php include nomad::includesDir()."/top.php" ?>
<?php include nomad::includesDir()."/crumbs.php" ?>


<!--RIGHT-START-->
<!--RIGHT-PLACEHOLDER-->
<!--RIGHT-END-->


<!--MAIN-START-->
<!--MAIN-PLACEHOLDER-->
<!--MAIN-END-->


<?php include nomad::includesDir()."/foot.php" ?>
</body>
</html>